
if __name__ == "__main__":
    main = open("Lexeter Source.py","r+")
    goal = open("Lexeter.py","r+")
    core = open("lib/core.py","r+")
    darkroom = open("lib/darkroom.py","r+")
    biome = open("lib/biome.py","r+")
    action = open("lib/action.py","r+")
    player = open("lib/player.py","r+")
    items = open("lib/items.py","r+")
    goal.seek(0)
    goal.truncate()
    goal.write(core.read())
    goal.write(biome.read())
    goal.write(darkroom.read())
    goal.write(action.read())
    goal.write(items.read())
    goal.write(player.read())
    goal.write(main.read())